version: '3'
services:
  db:
    image: circleci/mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "43306:3306"
  backend:
    build: ./backend
    ports:
      - 8000:3000
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    volumes:
      - ./backend:/app
      - backend-bundle:/usr/local/bundle
    depends_on:
      - db
    tty: true
    stdin_open: true
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    command: /bin/sh -c "npm run dev"
    volumes:
      - ./frontend:/app
      - frontend-node_modules:/app/node_modules
    tty: true
volumes:
  db-data:
  backend-bundle:
  frontend-node_modules: